services:
  jupyter:
    image: abhishek1009/python:latest
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./basics:/workspace/src
    working_dir: /workspace/src
    command: jupyter-notebook --ip=0.0.0.0 --allow-root --NotebookApp.token=''
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data





volumes:
  pgdata: