events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost 127.0.0.1;

        location /image-scan {
            alias /reports/trivy-image.html;
            try_files $uri =404;
            default_type text/html;
        }

        location /helm-scan {
            alias /reports/trivy-helm.html;
            try_files $uri =404;
            default_type text/html;
        }

        location /fs-scan {
            alias /reports/trivy-fs.html;
            try_files $uri =404;
            default_type text/html;
        }
    }
}
