apiVersion: v1
kind: Service
metadata:
  name: {{ include "prime-api.fullname" . }}-api
  labels:
    app: api
    {{- include "prime-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}
    protocol: TCP
  selector:
    app: api
    {{- include "prime-api.selectorLabels" . | nindent 4 }}