apiVersion: v1
kind: Service
metadata:
  name: {{ include "prime-api.fullname" . }}-redis
  labels:
    app: redis
    {{- include "prime-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
  selector:
    app: redis
    {{- include "prime-api.selectorLabels" . | nindent 4 }}