apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prime-api.fullname" . }}-redis
  labels:
    app: redis
    {{- include "prime-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      {{- include "prime-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
        {{- include "prime-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        # Command to enable persistence, so the PV is useful
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: {{ .Values.redis.port }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ .Values.redis.pvc.name }}